<div class='container'>
  <h1>Add New RSS Feed URL</h1>
  <p>
      Please fill out the following form and click the <i>Submit</i> button.
  </p>
  <div class="row">
      <div class="col-md-6">
        <form method="post" action="">
         <input type="text" name="feedurl" placeholder="Enter website feed URL">
         <input type="submit" value="Submit" name="submit">
         <?php if($message){?> <span> <?php echo $message?></span><?php }?>
        </form>
      </div>
   </div>
</div>
